apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: openshift-logging
data:
  rclone.conf: |
    [source]
    type = s3
    provider = Other
    env_auth = false
    access_key_id = ${SOURCE_ACCESS_KEY}
    secret_access_key = ${SOURCE_SECRET_KEY}
    endpoint = https://s3.openshift-storage.svc:443
    acl = private
    insecure_skip_verify = true

    [target]
    type = s3
    provider = Other
    env_auth = false
    access_key_id = ${TARGET_ACCESS_KEY}
    secret_access_key = ${TARGET_SECRET_KEY}
    endpoint = https://rgw.openshift-storage.svc:443
    acl = private
    insecure_skip_verify = true 