apiVersion: v1
kind: Service
metadata:
  name: openshift-analyzer
  labels:
    app: openshift-analyzer
spec:
  selector:
    app: openshift-analyzer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP 