apiVersion: apps/v1
kind: Deployment
metadata:
  name: openshift-analyzer
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: DEBUG
          value: "true"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi 