apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

patches:
- path: patches/deployment.yaml
  target:
    kind: Deployment
    name: openshift-analyzer

configMapGenerator:
- name: openshift-analyzer-config
  behavior: merge
  files:
  - config.yaml=patches/config.yaml 